version: "3"

services:
  tnsriodb:
    image: tnsriodb_img
    container_name: tnsriodb
    hostname: ${HOSTNAME}
    build:
      context: .
      dockerfile: ./service/redis/Dockerfile.redis.cpu
    ports:
      - '6379:6379'
    volumes:
      - $HOME/tnsrio/data:/data  # Bind mount a volume from host ./data/redis to container /data
      - $HOME/tnsrio/modules:/usr/lib/redis/modules
    networks:
      - data_layer
networks:
  data_layer:
    driver: bridge