FROM redis:latest

RUN apt-get update 
RUN apt-get install -y ca-certificates

COPY ./service/redis/conf/redis.conf /usr/local/etc/redis/redis.conf

EXPOSE 6379

CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]